# THYMELEAF (ThymeleafAutoConfiguration)
# 开启模板缓存（默认值： true ）
spring.thymeleaf.cache=true
# 检查模板是否存在，然后再呈现
spring.thymeleaf.check-template=true
# 检查模板位置是否正确（默认值 :true ）
spring.thymeleaf.check-template-location=true
#Content-Type 的值（默认值： text/html ）
spring.thymeleaf.content-type=text/html
# 开启 MVC Thymeleaf 视图解析（默认值： true ）
spring.thymeleaf.enabled=true
# 模板编码
spring.thymeleaf.encoding=UTF-8
# 要被排除在解析之外的视图名称列表，⽤逗号分隔
spring.thymeleaf.excluded-view-names=
# 要运⽤于模板之上的模板模式。另⻅ StandardTemplate-ModeHandlers( 默认值： HTML5)
spring.thymeleaf.mode=HTML5
# 在构建 URL 时添加到视图名称前的前缀（默认值： classpath:/templates/ ）
spring.thymeleaf.prefix=classpath:/templates/
# 在构建 URL 时添加到视图名称后的后缀（默认值： .html ）
spring.thymeleaf.suffix=.html
# 应用服务 WEB 访问端口
server.port=${PORT:8080}



spring.devtools.add-properties=false

# 开启热部署
spring.devtools.restart.enabled=true
# 设置重启排除目录
spring.devtools.restart.exclude=static/**,public/**,templates/**
# 触发文件（修改此文件立即重启）
#spring.devtools.restart.trigger-file=.reloadtrigger


# 数据库配置
spring.datasource.url=jdbc:mysql://172.10.10.115:3306/dhg?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=DongBaoSoft
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#mybatis配置
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.dongbao.test_demo3.entity
mybatis.configuration.map-underscore-to-camel-case=true

#mybatis-plus配置(不能同时配置mybatis和mybatis-plus, 否则报错)
# 使用 MyBatis-Plus 配置，它会自动包含 MyBatis 功能
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus.mapper-locations=classpath:mapper/*.xml
mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.global-config.db-config.id-type=AUTO
# 主键类型 AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
mybatis-plus.type-aliases-package=com.dongbao.test_demo3.entity


# swagger配置
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.version=1.0.0
springdoc.default-consumes-media-type=application/json
springdoc.default-produces-media-type=application/json



# Redis 基础配置
spring.redis.host=172.16.199.19
spring.redis.port=6380
#spring.redis.password=your_password
#spring.redis.database=16

# 连接池配置
spring.redis.lettuce.pool.max-active=8
spring.redis.lettuce.pool.max-idle=8
spring.redis.lettuce.pool.min-idle=0
#spring.redis.lettuce.pool.max-wait=-1ms

# 超时配置
spring.redis.timeout=2000ms
spring.redis.connect-timeout=1000ms


#logback日志级别配置
#日志文件路径
#logging.file.path: ./logs
##日志文件名称
#logging.file.name: demo.log
##指定包名的日志级别
#logging.level.com.dongbao.test_demo3.Exception: INFO
#logging.level.com.dongbao.test_demo3.controller: DEBUG
##Spring 框架相关日志级别
#logging.level.org.springframework: WARN
##日志文件格式
#logging.pattern.file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"